{
 "title": "用户级GPU使用情况",
 "tags": [
  "GPU",
  "Monitor"
 ],
 "time": { "from": "2026-01-31T16:00:00.000Z", "to": "2026-02-28T15:59:59.000Z" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "服务器实例",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,instance)"
    }
   },
   {
    "name": "user",
    "label": "用户",
    "query": "query_result(max by (user) (present_over_time(gpu_process_memory_usage_bytes{user!=\"\", user!=\"root\", user!=\"ollama\"}[$__range])))"
   }
  ]
 },
 "panels": [
  {
   "title": "🖥️ 在线显卡总数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_TEMP{job=~\"gpu-dcgm|.*\", instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "👥 当前活跃用户",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (user) (gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\"} > 0)) or vector(0)"
    }
   ]
  },
  {
   "title": "⚡ 平均集群负载",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "🔥 最高温度",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "🏆 用户使用时长排行榜 (Leaderboard)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "targets": [
    {
     "expr": "sum_over_time(\r\n  (\r\n    sum by (user, instance, gpu_index, gpu_name) (\r\n      gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\"} > bool 0\r\n    )\r\n  )[24h:1m]\r\n) \r\n/ 60\r\n",
     "legendFormat": "T1D"
    },
    {
     "expr": "sum_over_time(\r\n  (\r\n    sum by (user, instance, gpu_index, gpu_name) (\r\n      gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\", user!=\"\", gpu_name!=\"\"} > bool 0\r\n    )\r\n  )[7d:1m]\r\n) \r\n/ 60\r\n> 0",
     "legendFormat": "T1W"
    },
    {
     "expr": "sum_over_time(\r\n  (\r\n    sum by (user, instance, gpu_index, gpu_name) (\r\n      gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\", user!=\"\", gpu_name!=\"\"} > bool 0\r\n    )\r\n  )[30d:1m]\r\n) \r\n/ 60\r\n> 0",
     "legendFormat": "T1M"
    },
    {
     "expr": "sum_over_time(\r\n  (\r\n    sum by (user, instance, gpu_index, gpu_name) (\r\n      gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\", user!=\"\", gpu_name!=\"\"} > bool 0\r\n    )\r\n  )[$__range:1m]\r\n) \r\n/ 60\r\n> 0",
     "legendFormat": "T_CUSTOM"
    }
   ]
  },
  {
   "title": "📊 过去 1 天占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  sum_over_time(\r\n    (gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\"} > bool 0)[24h:1m]\r\n  )\r\n) by (user) / 60",
     "legendFormat": "{{user}}"
    },
    {
     "expr": "label_replace(\r\n  vector(\r\n    (\r\n      scalar(\r\n        count(\r\n          count by (instance, gpu_index) (\r\n            present_over_time(gpu_process_memory_usage_bytes{instance=~\"$instance.*\"}[24h])\r\n          )\r\n        ) or vector(0)\r\n      ) * 24\r\n    ) \r\n    - \r\n    (\r\n      scalar(\r\n        sum(\r\n          sum_over_time(\r\n            (gpu_process_memory_usage_bytes{instance=~\"$instance.*\"} > bool 0)[24h:1m]\r\n          )\r\n        ) \r\n      ) / 60\r\n    )\r\n  ), \r\n  \"user\", \"😴 空闲 (Idle)\", \"\", \"\"\r\n)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "📊 过去 1 周占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  sum_over_time(\r\n    (gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\"} > bool 0)[7d:1m]\r\n  )\r\n) by (user) / 60",
     "legendFormat": "{{user}}"
    },
    {
     "expr": "label_replace(\r\n  vector(\r\n    (\r\n      scalar(\r\n        count(\r\n          count by (instance, gpu_index) (\r\n            present_over_time(gpu_process_memory_usage_bytes{instance=~\"$instance.*\"}[7d])\r\n          )\r\n        ) or vector(0)\r\n      ) * 168\r\n    ) \r\n    - \r\n    (\r\n      scalar(\r\n        sum(\r\n          sum_over_time(\r\n            (gpu_process_memory_usage_bytes{instance=~\"$instance.*\"} > bool 0)[7d:1m]\r\n          )\r\n        ) \r\n      ) / 60\r\n    )\r\n  ), \r\n  \"user\", \"😴 空闲 (Idle)\", \"\", \"\"\r\n)\r\n",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "📊 过去 1 月占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  sum_over_time(\r\n    (gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\"} > bool 0)[30d:1m]\r\n  )\r\n) by (user) / 60",
     "legendFormat": "{{user}}"
    },
    {
     "expr": "label_replace(\r\n  vector(\r\n    (\r\n      scalar(\r\n        count(\r\n          count by (instance, gpu_index) (\r\n            present_over_time(gpu_process_memory_usage_bytes{instance=~\"$instance.*\"}[30d])\r\n          )\r\n        ) or vector(0)\r\n      ) * 720\r\n    ) \r\n    - \r\n    (\r\n      scalar(\r\n        sum(\r\n          sum_over_time(\r\n            (gpu_process_memory_usage_bytes{instance=~\"$instance.*\"} > bool 0)[30d:1m]\r\n          )\r\n        ) \r\n      ) / 60\r\n    )\r\n  ), \r\n  \"user\", \"😴 空闲 (Idle)\", \"\", \"\"\r\n)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "📊 所选时间占比  ( ${__from:date:MM.DD}~${__to:date:MM.DD})",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  sum_over_time(\r\n    (gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\"} > bool 0)[$__range:1m]\r\n  )\r\n) by (user) / 60",
     "legendFormat": "{{user}}"
    },
    {
     "expr": "label_replace(\r\n  vector(\r\n    (\r\n      scalar(\r\n        count(\r\n          count by (instance, gpu_index) (\r\n            present_over_time(gpu_process_memory_usage_bytes{instance=~\"$instance.*\"}[$__range])\r\n          )\r\n        ) or vector(0)\r\n      ) * ($__range_s / 3600)\r\n    ) \r\n    - \r\n    (\r\n      scalar(\r\n        sum(\r\n          sum_over_time(\r\n            (gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\"} > bool 0)[$__range:1m]\r\n          )\r\n        ) \r\n      ) / 60\r\n    )\r\n  ), \r\n  \"user\", \"😴 空闲 (Idle)\", \"\", \"\"\r\n)\r\n",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "🕵️ 深度监管列表 (Squatters Check - Zombie Hunter Edition)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(sum by (instance, gpu_index, user) (gpu_process_memory_usage_bytes{instance=~\"$instance.*\", user=~\"$user\", user!=\"\"}), \"uid\", \"_\", \"instance\", \"gpu_index\")",
     "legendFormat": "UserMem"
    },
    {
     "expr": "label_join(avg by (instance, gpu_index) (DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance.*\"}), \"uid\", \"_\", \"instance\", \"gpu_index\")",
     "legendFormat": "RawUtil"
    },
    {
     "expr": "label_join(max by (instance, gpu_index, gpu_name) (gpu_memory_total_bytes{instance=~\"$instance.*\"}), \"uid\", \"_\", \"instance\", \"gpu_index\")",
     "legendFormat": "TotalMem"
    }
   ]
  }
 ]
}